DROP TABLE "FEE";

CREATE TABLE "FEE" (
	"APT_NO"	VARCHAR2(30)		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"FEE_MONTH"	NUMBER		NOT NULL,
	"DUE_DATE"	DATE		NOT NULL,
	"APT_FEE"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "FEE"."USER_NO" IS 'SEQ_UNO';

DROP TABLE "RESERVE";

CREATE TABLE "RESERVE" (
	"RESERVE_NO"	NUMBER		NOT NULL,
	"START_DATE"	DATE		NULL,
	"END_DATE"	DATE		NULL,
	"FACILITY"	VARCHAR2(10)		NULL,
	"SEAT_NUMBER"	NUMBER		NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"STATUS"	VARCHAR2(1)		NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "RESERVE"."RESERVE_NO" IS 'SEQ_RNO';

COMMENT ON COLUMN "RESERVE"."FACILITY" IS '독서실:ST, 미니짐:MG, 골프:GF';

COMMENT ON COLUMN "RESERVE"."SEAT_NUMBER" IS '독서실:100~, 골프:1~';

COMMENT ON COLUMN "RESERVE"."USER_NO" IS 'SEQ_UNO';

COMMENT ON COLUMN "RESERVE"."STATUS" IS 'Y / N / Z(독서실: 임박)';

DROP TABLE "NOTICE";

CREATE TABLE "NOTICE" (
	"NOTICE_NO"	NUMBER		NOT NULL,
	"NOTICE_TITLE"	VARCHAR2(500)		NOT NULL,
	"NOTICE_CATEGORY"	VARCHAR2(15)		NOT NULL,
	"NOTICE_CONTENT"	VARCHAR2(3000)		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(200)		NULL,
	"CHANGE_NAME"	VARCHAR2(200)		NULL,
	"NOTICE_CALENDER"	VARCHAR2(100)		NULL,
	"NOTICE_START_DATE"	DATE		NULL,
	"NOTICE_END_DATE"	DATE		NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS 'SEQ_NNO';

COMMENT ON COLUMN "NOTICE"."NOTICE_CATEGORY" IS '[공지] / [행사]/[알림]';

COMMENT ON COLUMN "NOTICE"."USER_NO" IS 'SEQ_UNO';

COMMENT ON COLUMN "NOTICE"."STATUS" IS '존재 Y / 삭제 N';

DROP TABLE "BOARD";

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(500)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(3000)		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(200)		NULL,
	"CHANGE_NAME"	VARCHAR2(200)		NULL,
	"COUNT"	NUMBER	DEFAULT 0	NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NULL,
	"BOARD_CATEGORY"	VARCHAR2(50)	DEFAULT '[일반]'	NOT NULL,
	"USER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS 'SEQ_BNO';

COMMENT ON COLUMN "BOARD"."STATUS" IS '존재:Y/삭제:N';

COMMENT ON COLUMN "BOARD"."BOARD_CATEGORY" IS '[맘] , [건의], [판매], [정보]';

COMMENT ON COLUMN "BOARD"."USER_NO" IS 'SEQ_UNO';

DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"USER_NO"	NUMBER		NOT NULL,
	"APT_NO"	VARCHAR2(30)		NOT NULL,
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"USER_PWD"	VARCHAR2(100)		NOT NULL,
	"USER_NAME"	VARCHAR2(30)		NOT NULL,
	"BIRTHDAY"	VARCHAR2(20)		NOT NULL,
	"PHONE"	VARCHAR2(20)		NOT NULL,
	"EMAIL"	VARCHAR2(30)		NULL,
	"STATUS"	VARCHAR2(5)	DEFAULT 'W'	NOT NULL,
    CONSTRAINT USER_ID_UQ UNIQUE (USER_ID)
);

COMMENT ON COLUMN "MEMBER"."USER_NO" IS 'SEQ_UNO';

COMMENT ON COLUMN "MEMBER"."USER_ID" IS 'UNIQUE';

COMMENT ON COLUMN "MEMBER"."STATUS" IS '존재 : Y/ 삭제 : N/ 대기 : W';

DROP TABLE "CHAT";

CREATE TABLE "CHAT" (
	"CHAT_NO"	NUMBER		NOT NULL,
	"CHAT_CONTENT"	VARCHAR2(2000)		NOT NULL,
	"CHAT_SENDTIME"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CHAT_CODE"	NUMBER	DEFAULT 1	NOT NULL,
	"USER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CHAT"."CHAT_NO" IS 'SEQ_CHNO';

COMMENT ON COLUMN "CHAT"."CHAT_CODE" IS '주민단톡:1 / 경비실:2 / 관리소:3';

COMMENT ON COLUMN "CHAT"."USER_NO" IS 'SEQ_UNO';

DROP TABLE "VISIT";

CREATE TABLE "VISIT" (
	"VISIT_NO"	NUMBER		NOT NULL,
	"VISIT_CATEGORY"	VARCHAR2(50)		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"VISIT_START_DATE"	DATE		NULL,
	"VISIT_END_DATE"	DATE		NULL,
	"VISIT_STATUS"	VARCHAR2(1)	DEFAULT 'W'	NOT NULL,
	"VISIT_CONTENT"	VARCHAR2(3000)		NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "VISIT"."VISIT_NO" IS 'SEQ_VNO';

COMMENT ON COLUMN "VISIT"."VISIT_CATEGORY" IS '난방, 수도, 전기,가스,소독';

COMMENT ON COLUMN "VISIT"."USER_NO" IS 'SEQ_UNO';

COMMENT ON COLUMN "VISIT"."VISIT_STATUS" IS '승인 Y / 대기 W / 반려, 삭제 N';

DROP TABLE "PARKING";

CREATE TABLE "PARKING" (
	"CAR_NO"	VARCHAR2(20)		NOT NULL,
	"CAR_PHONE"	VARCHAR2(20)		NULL,
	"STATUS"	VARCHAR2(5)		NULL,
	"CAR_CATEGORY"	NUMBER		NOT NULL,
	"CAR_DATE"	DATE		NULL,
	"CAR_PURPOSE"	VARCHAR2(50)		NULL,
	"USER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PARKING"."STATUS" IS '승인:Y  대기:W  반려,삭제:N';

COMMENT ON COLUMN "PARKING"."CAR_CATEGORY" IS '1:입주민, 2:방문차량';

COMMENT ON COLUMN "PARKING"."CAR_PURPOSE" IS '방문차량 방문목적';

COMMENT ON COLUMN "PARKING"."USER_NO" IS 'SEQ_UNO';

DROP TABLE "REPLY";

CREATE TABLE "REPLY" (
	"REPLY_NO"	NUMBER		NOT NULL,
	"REPLY_CONTENT"	VARCHAR2(200)		NOT NULL,
	"REF_BNO"	NUMBER		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NULL,
	"USER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "REPLY"."REF_BNO" IS 'BOARD_NO';

COMMENT ON COLUMN "REPLY"."STATUS" IS '존재:Y / 삭제 : N';

COMMENT ON COLUMN "REPLY"."USER_NO" IS 'SEQ_UNO';

ALTER TABLE "FEE" ADD CONSTRAINT "PK_FEE" PRIMARY KEY (
	"APT_NO"
);

ALTER TABLE "RESERVE" ADD CONSTRAINT "PK_RESERVE" PRIMARY KEY (
	"RESERVE_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"USER_NO"
);

ALTER TABLE "CHAT" ADD CONSTRAINT "PK_CHAT" PRIMARY KEY (
	"CHAT_NO"
);

ALTER TABLE "VISIT" ADD CONSTRAINT "PK_VISIT" PRIMARY KEY (
	"VISIT_NO"
);

ALTER TABLE "PARKING" ADD CONSTRAINT "PK_PARKING" PRIMARY KEY (
	"CAR_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
	"REPLY_NO"
);

ALTER TABLE "FEE" ADD CONSTRAINT "FK_MEMBER_TO_FEE_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "RESERVE" ADD CONSTRAINT "FK_MEMBER_TO_RESERVE_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_MEMBER_TO_NOTICE_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "CHAT" ADD CONSTRAINT "FK_MEMBER_TO_CHAT_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "VISIT" ADD CONSTRAINT "FK_MEMBER_TO_VISIT_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "PARKING" ADD CONSTRAINT "FK_MEMBER_TO_PARKING_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_BOARD_TO_REPLY_1" FOREIGN KEY (
	"REF_BNO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_MEMBER_TO_REPLY_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

DROP SEQUENCE SEQ_RNO;
DROP SEQUENCE SEQ_VNO;
DROP SEQUENCE SEQ_CHNO;
DROP SEQUENCE SEQ_UNO;
DROP SEQUENCE SEQ_VONO;
DROP SEQUENCE SEQ_NNO;
DROP SEQUENCE SEQ_BNO;

CREATE SEQUENCE SEQ_RNO
NOCACHE;

CREATE SEQUENCE SEQ_VNO
NOCACHE;

CREATE SEQUENCE SEQ_CHNO
NOCACHE;

CREATE SEQUENCE SEQ_UNO
NOCACHE;

CREATE SEQUENCE SEQ_VONO
NOCACHE;

CREATE SEQUENCE SEQ_NNO
NOCACHE;

CREATE SEQUENCE SEQ_BNO
NOCACHE;

INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL,'관리사무소', 'admin', '$2a$10$1nW/oAclCmFb72HM4pXihuizrpPX7zz2ikemFdJk1WWkrDxXxNInO', '관리자', '650101', '01012341234', 'admin@kh.or.kr', 'Y');

INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL,'1동101호', 'user01', '$2a$10$Tj2EpG0n2ekHAvWvP9i3YeYlHXq0RwBvjaLi4kokWdwYn5CIPqyUG', '홍길동', '970514', '01011112222', 'user01@kh.or.kr', 'Y');

COMMIT;