DROP USER JAVER CASCADE;
CREATE USER JAVER IDENTIFIED BY JAVER;
GRANT CONNECT, RESOURCE TO JAVER;

DROP TABLE MEMBER;
CREATE TABLE "MEMBER" (
	"USER_ID"	VARCHAR2(40)		NOT NULL,
	"USER_PWD"	VARCHAR2(100)		NOT NULL,
	"USER_NAME"	VARCHAR2(20)		NOT NULL,
	"EMAIL"	VARCHAR2(50)		NULL,
	"PHONE"	VARCHAR2(20)		NOT NULL,
    "BIRTH" DATE NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NULL
);


