DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"USER_ID"	VARCHAR2(40)		NOT NULL,
	"USER_PWD"	VARCHAR2(100)		NOT NULL,
	"USER_NAME"	VARCHAR2(20)		NOT NULL,
	"EMAIL"	VARCHAR2(50)		NULL,
	"ADDRESS"	VARCHAR2(1000)		NOT NULL,
	"PHONE"	VARCHAR2(20)		NOT NULL,
	"NICKNAME"	VARCHAR2(50)		NOT NULL,
	"COOK_LEVEL"	VARCHAR2(10)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NULL,
	"FAVORITE_FOOD"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MEMBER"."USER_ID" IS '회원아이디';

COMMENT ON COLUMN "MEMBER"."USER_PWD" IS '회원비밀번호';

COMMENT ON COLUMN "MEMBER"."USER_NAME" IS '회원이름';

COMMENT ON COLUMN "MEMBER"."EMAIL" IS '이메일';

COMMENT ON COLUMN "MEMBER"."ADDRESS" IS '주소';

COMMENT ON COLUMN "MEMBER"."PHONE" IS '핸드폰';

COMMENT ON COLUMN "MEMBER"."NICKNAME" IS '닉네임';

COMMENT ON COLUMN "MEMBER"."COOK_LEVEL" IS '요리 레벨';

COMMENT ON COLUMN "MEMBER"."CREATE_DATE" IS '가입일';

COMMENT ON COLUMN "MEMBER"."MODIFY_DATE" IS '회원정보수정일';

COMMENT ON COLUMN "MEMBER"."STATUS" IS '탈퇴여부';

COMMENT ON COLUMN "MEMBER"."FAVORITE_FOOD" IS '선호음식(나라별)';

DROP TABLE "NOTICE";

CREATE TABLE "NOTICE" (
	"NOTICE_NO"	NUMBER		NOT NULL,
	"NOTICE_TITLE"	VARCHAR2(50)		NOT NULL,
	"NOTICE_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"NOTICE_COUNT"	NUMBER	DEFAULT 0	NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"STATUS"	VARCHAR2(2)	DEFAULT 'Y'	NULL,
	"NOTICE_WRITER"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS '공지사항번호';

COMMENT ON COLUMN "NOTICE"."NOTICE_TITLE" IS '공지사항제목';

COMMENT ON COLUMN "NOTICE"."NOTICE_CONTENT" IS '공지사항내용';

COMMENT ON COLUMN "NOTICE"."NOTICE_COUNT" IS '공지사항조회수';

COMMENT ON COLUMN "NOTICE"."CREATE_DATE" IS '생성날짜';

COMMENT ON COLUMN "NOTICE"."MODIFY_DATE" IS '수정날짜';

COMMENT ON COLUMN "NOTICE"."STATUS" IS '삭제여부';

COMMENT ON COLUMN "NOTICE"."NOTICE_WRITER" IS '공지사항 작성자';

DROP TABLE "RECIPE";

CREATE TABLE "RECIPE" (
	"PE_NO"	NUMBER		NOT NULL,
	"PE_TITLE"	VARCHAR2(100)		NOT NULL,
	"PE_INTRODUCE"	VARCHAR2(4000)		NOT NULL,
	"PE_WRITER"	VARCHAR2(40)		NOT NULL,
	"PE_FOOD_AMOUNT"	VARCHAR2(1000)		NOT NULL,
	"PE_COOK_TIME"	VARCHAR2(1000)		NOT NULL,
	"PE_COOK_LEVEL"	VARCHAR2(1000)		NOT NULL,
	"PE_LIKECOUNT"	NUMBER	DEFAULT 0	NULL,
	"PE_CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PE_MODIFY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PE_STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NULL,
	"BOARD_TYPE"	NUMBER	DEFAULT 1	NULL,
	"NAT_CAT_NO"	NUMBER		NOT NULL,
	"KIND_CAT_NO"	NUMBER		NOT NULL,
	"PRO_CAT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RECIPE"."PE_NO" IS '레시피 번호';

COMMENT ON COLUMN "RECIPE"."PE_TITLE" IS '레시피 제목';

COMMENT ON COLUMN "RECIPE"."PE_INTRODUCE" IS '요리소개';

COMMENT ON COLUMN "RECIPE"."PE_WRITER" IS '레시피 글쓴이(USERID 로 조인후 닉네임을 가져온다.)';

COMMENT ON COLUMN "RECIPE"."PE_FOOD_AMOUNT" IS '요리 양(몇인분?)';

COMMENT ON COLUMN "RECIPE"."PE_COOK_TIME" IS '요리 시간';

COMMENT ON COLUMN "RECIPE"."PE_COOK_LEVEL" IS '요리 난이도';

COMMENT ON COLUMN "RECIPE"."PE_LIKECOUNT" IS '좋아요 개수';

COMMENT ON COLUMN "RECIPE"."PE_CREATE_DATE" IS '레시피 등록일';

COMMENT ON COLUMN "RECIPE"."PE_MODIFY_DATE" IS '레시피 수정일';

COMMENT ON COLUMN "RECIPE"."PE_STATUS" IS '삭제여부';

COMMENT ON COLUMN "RECIPE"."BOARD_TYPE" IS '레시피1/레시판2';

COMMENT ON COLUMN "RECIPE"."NAT_CAT_NO" IS '나라별 카테고리';

COMMENT ON COLUMN "RECIPE"."KIND_CAT_NO" IS '종류별 카테고리';

COMMENT ON COLUMN "RECIPE"."PRO_CAT_NO" IS '재료별 카테고리';

DROP TABLE "QNA";

CREATE TABLE "QNA" (
	"QNA_NO"	NUMBER		NOT NULL,
	"QNA_TITLE"	VARCHAR2(100)		NULL,
	"QNA_CONTENT"	VARCHAR2(4000)		NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NULL,
	"CREATE_DATE"	DATE		NULL,
	"MODIFY_DATE"	DATE		NULL,
	"PRODUCT_NO"	NUMBER		NOT NULL,
	"QNA_WRITER"	VARCHAR2(20)		NOT NULL,
	"QNA_ANSWER_ST"	VARCHAR2(1)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "QNA"."QNA_NO" IS '문의사항 번호';

COMMENT ON COLUMN "QNA"."QNA_TITLE" IS '문의사항 제목';

COMMENT ON COLUMN "QNA"."QNA_CONTENT" IS '문의사항 내용';

COMMENT ON COLUMN "QNA"."STATUS" IS '문의사항 삭제여부';

COMMENT ON COLUMN "QNA"."CREATE_DATE" IS '문의사항 작성일';

COMMENT ON COLUMN "QNA"."MODIFY_DATE" IS '문의사항 수정일';

COMMENT ON COLUMN "QNA"."PRODUCT_NO" IS '식재료 번호';

COMMENT ON COLUMN "QNA"."QNA_WRITER" IS '회원아이디';

COMMENT ON COLUMN "QNA"."QNA_ANSWER_ST" IS '문의사항 답변여부';

DROP TABLE "COMMENT";

CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"COMMENT_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NULL,
	"COMMENT_WRITER"	VARCHAR2(20)		NOT NULL,
	"REF_PE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글번호';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글내용';

COMMENT ON COLUMN "COMMENT"."CREATE_DATE" IS '댓글작성일';

COMMENT ON COLUMN "COMMENT"."MODIFY_DATE" IS '댓글수정일';

COMMENT ON COLUMN "COMMENT"."STATUS" IS '댓글삭제여부';

COMMENT ON COLUMN "COMMENT"."COMMENT_WRITER" IS '댓글작성자';

COMMENT ON COLUMN "COMMENT"."REF_PE_NO" IS '레시피 번호';

DROP TABLE "PQNA";

CREATE TABLE "PQNA" (
	"PQNA_NO"	NUMBER		NOT NULL,
	"PQNA_TITLE"	VARCHAR2(100)		NULL,
	"PQNA_CONTENT"	VARCHAR2(4000)		NULL,
	"STATUS"	VARCHAR2(10)	DEFAULT 'Y'	NULL,
	"CREATE_DATE"	DATE DEFAULT SYSDATE NULL,
	"MODIFY_DATE"	DATE DEFAULT SYSDATE NULL,
	"PQNA_ANSWER_ST"	VARCHAR2(1)	DEFAULT 'N'	NULL,
	"PQNA_WRITER"	VARCHAR2(40)		NOT NULL
);

COMMENT ON COLUMN "PQNA"."PQNA_NO" IS '1:1문의사항 번호';

COMMENT ON COLUMN "PQNA"."PQNA_TITLE" IS '1:1문의사항 제목';

COMMENT ON COLUMN "PQNA"."PQNA_CONTENT" IS '1:1문의사항 내용';

COMMENT ON COLUMN "PQNA"."STATUS" IS '1:1문의사항 삭제여부';

COMMENT ON COLUMN "PQNA"."CREATE_DATE" IS '1:1문의사항 작성일';

COMMENT ON COLUMN "PQNA"."MODIFY_DATE" IS '1:1문의사항 수정일';

COMMENT ON COLUMN "PQNA"."PQNA_ANSWER_ST" IS '문의사항 답변여부';

COMMENT ON COLUMN "PQNA"."PQNA_WRITER" IS '1:1문의사항 작성자';

DROP TABLE "CART";

CREATE TABLE "CART" (
	"CART_NO"	NUMBER		NOT NULL,
	"CART_AMOUNT"	NUMBER		NOT NULL,
	"CART_STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NULL,
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"PRO_NO"	NUMBER		NOT NULL,
    "ORDER_STATUS" VARCHAR2(1) DEFAULT 'N' NULL
);

COMMENT ON COLUMN "CART"."CART_NO" IS '장바구니 번호';

COMMENT ON COLUMN "CART"."CART_AMOUNT" IS '제품 수량';

COMMENT ON COLUMN "CART"."CART_STATUS" IS '체크여부(Y/N)';

COMMENT ON COLUMN "CART"."USER_ID" IS '회원아이디';

COMMENT ON COLUMN "CART"."PRO_NO" IS '식재료 번호';

COMMENT ON COLUMN "CART"."ORDER_STATUS" IS '결제여부';

DROP TABLE "REVIEW";

CREATE TABLE "REVIEW" (
	"RV_NO"	NUMBER		NOT NULL,
	"RV_TITLE"	VARCHAR2(100)		NOT NULL,
	"RV_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CREATE_DATE"	DATE DEFAULT SYSDATE NULL,
	"MODIFY_DATE"	DATE DEFAULT SYSDATE NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"RV_WRITER"	VARCHAR2(40)		NOT NULL,
	"RV_PRO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "REVIEW"."RV_NO" IS '리뷰번호';

COMMENT ON COLUMN "REVIEW"."RV_TITLE" IS '리뷰제목';

COMMENT ON COLUMN "REVIEW"."RV_CONTENT" IS '리뷰내용';

COMMENT ON COLUMN "REVIEW"."CREATE_DATE" IS '리뷰 작성일';

COMMENT ON COLUMN "REVIEW"."MODIFY_DATE" IS '리뷰 수정일';

COMMENT ON COLUMN "REVIEW"."STATUS" IS '리뷰 삭제여부';

COMMENT ON COLUMN "REVIEW"."PR_AMOUNT" IS '구매 수량';

COMMENT ON COLUMN "REVIEW"."RV_WRITER" IS '회원아이디';

COMMENT ON COLUMN "REVIEW"."RV_PRO" IS '식재료 번호';

DROP TABLE "PRODUCT";

CREATE TABLE "PRODUCT" (
	"PR_NO"	NUMBER		NOT NULL,
	"PR_NAME"	VARCHAR2(50)		NOT NULL,
	"PR_INTRODUCE"	VARCHAR2(300)		NULL,
	"PR_WEIGHT"	VARCHAR2(50)		NOT NULL,
	"PR_PRICE"	NUMBER		NOT NULL,
	"PR_ORIGIN"	VARCHAR2(100)		NOT NULL,
	"PR_CONTENT"	VARCHAR2(4000)		NULL,
	"STATUS"	VARCHAR2(2)	DEFAULT 'Y'	NOT NULL,
	"PR_LIKECOUNT"	NUMBER	DEFAULT 0	NULL,
	"PRO_CAT_NO"	NUMBER		NOT NULL,
    "CREATE_DATE" DATE DEFAULT SYSDATE NULL
);

COMMENT ON COLUMN "PRODUCT"."PR_NO" IS '식재료 번호';

COMMENT ON COLUMN "PRODUCT"."PR_NAME" IS '상품명';

COMMENT ON COLUMN "PRODUCT"."PR_INTRODUCE" IS '상품소개';

COMMENT ON COLUMN "PRODUCT"."PR_WEIGHT" IS '식재료 무게';

COMMENT ON COLUMN "PRODUCT"."PR_PRICE" IS '식재료 가격';

COMMENT ON COLUMN "PRODUCT"."PR_ORIGIN" IS '식재료 원산지';

COMMENT ON COLUMN "PRODUCT"."PR_CONTENT" IS '상품 설명';

COMMENT ON COLUMN "PRODUCT"."STATUS" IS '식재료 삭제 여부';

COMMENT ON COLUMN "PRODUCT"."PR_LIKECOUNT" IS '식재료 좋아요 갯수';

COMMENT ON COLUMN "PRODUCT"."PRO_CAT_NO" IS '카테고리 번호';

DROP TABLE "LIKE";

CREATE TABLE "LIKE" (
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"PE_NO"	NUMBER		NULL,
	"PR_NO"	NUMBER		NULL,
	"LIKE_STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NULL
);

COMMENT ON COLUMN "LIKE"."USER_ID" IS '회원아이디';

COMMENT ON COLUMN "LIKE"."PE_NO" IS '레시피 번호';

COMMENT ON COLUMN "LIKE"."PR_NO" IS '식재료 번호';

COMMENT ON COLUMN "LIKE"."LIKE_STATUS" IS '좋아요여부(무한방지)';

DROP TABLE "RECIPE_SAUCE";

CREATE TABLE "RECIPE_SAUCE" (
	"PE_NO"	NUMBER		NOT NULL,
	"SAUCE_NAME"	VARCHAR2(100)		NOT NULL,
	"SAUCE_AMOUNT"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "RECIPE_SAUCE"."PE_NO" IS '레시피 번호';

COMMENT ON COLUMN "RECIPE_SAUCE"."SAUCE_NAME" IS '소스이름';

COMMENT ON COLUMN "RECIPE_SAUCE"."SAUCE_AMOUNT" IS '소스양';

DROP TABLE "ORDERTABLE";

CREATE TABLE "ORDERTABLE" (
	"ORDER_NO"	VARCHAR2(30)		NOT NULL,
	"ORDER_PRO"	VARCHAR(100)		NULL,
	"ORDER_PRICE"	NUMBER		NULL,
	"ORDER_AMOUNT"	NUMBER		NULL,
	"ORDER_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"DELIVERY_STATUS"	VARCHAR2(1)	DEFAULT 'N'	NULL,
	"USER_ID"	VARCHAR2(40)		NOT NULL
);

COMMENT ON COLUMN "ORDERTABLE"."ORDER_NO" IS '주문번호';

COMMENT ON COLUMN "ORDERTABLE"."ORDER_PRO" IS '주문상품명';

COMMENT ON COLUMN "ORDERTABLE"."ORDER_PRICE" IS '주문금액';

COMMENT ON COLUMN "ORDERTABLE"."ORDER_AMOUNT" IS '주문한 상품 개수';

COMMENT ON COLUMN "ORDERTABLE"."ORDER_DATE" IS '주문일자';

COMMENT ON COLUMN "ORDERTABLE"."DELIVERY_STATUS" IS '배송상태';

COMMENT ON COLUMN "ORDERTABLE"."USER_ID" IS '회원아이디(구매자)';

DROP TABLE "QNA_ANSWER";

CREATE TABLE "QNA_ANSWER" (
	"QNA_NO"	NUMBER		NOT NULL,
	"ANS_WRITER"	VARCHAR2(20)	DEFAULT 'admin'	NULL,
	"ANS_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"STATUS"	VARCHAR2(10)	DEFAULT 'Y'	NULL
);

COMMENT ON COLUMN "QNA_ANSWER"."QNA_NO" IS '문의사항 번호';

COMMENT ON COLUMN "QNA_ANSWER"."ANS_WRITER" IS '답변 작성자';

COMMENT ON COLUMN "QNA_ANSWER"."ANS_CONTENT" IS '답변 내용';

COMMENT ON COLUMN "QNA_ANSWER"."CREATE_DATE" IS '답변 날짜';

COMMENT ON COLUMN "QNA_ANSWER"."MODIFY_DATE" IS '수정날짜';

COMMENT ON COLUMN "QNA_ANSWER"."STATUS" IS '삭제여부';

DROP TABLE "RECIPE_PRODUCT";

CREATE TABLE "RECIPE_PRODUCT" (
	"PE_NO"	NUMBER		NOT NULL,
	"PRO_NAME"	VARCHAR2(100)		NOT NULL,
	"PRO_AMOUNT"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "RECIPE_PRODUCT"."PE_NO" IS '레시피 번호';

COMMENT ON COLUMN "RECIPE_PRODUCT"."PRO_NAME" IS '재료이름';

COMMENT ON COLUMN "RECIPE_PRODUCT"."PRO_AMOUNT" IS '재료양';

DROP TABLE "PRO_CATEGORY";

CREATE TABLE "PRO_CATEGORY" (
	"PRO_CAT_NO"	NUMBER		NOT NULL,
	"CATE_VALUE"	VARCHAR2(30)		NULL
);

COMMENT ON COLUMN "PRO_CATEGORY"."PRO_CAT_NO" IS '카테고리 번호';

COMMENT ON COLUMN "PRO_CATEGORY"."CATE_VALUE" IS '재료 이름';

DROP TABLE "KIND_CATEGORY";

CREATE TABLE "KIND_CATEGORY" (
	"KIND_CAT_NO"	NUMBER		NOT NULL,
	"CATE_VALUE"	VARCHAR2(30)		NULL
);

COMMENT ON COLUMN "KIND_CATEGORY"."KIND_CAT_NO" IS '카테고리 번호';

COMMENT ON COLUMN "KIND_CATEGORY"."CATE_VALUE" IS '종류 이름';

DROP TABLE "NAT_CATEGORY";

CREATE TABLE "NAT_CATEGORY" (
	"NAT_CAT_NO"	NUMBER		NOT NULL,
	"NAT_VALUE"	VARCHAR2(30)		NULL
);

COMMENT ON COLUMN "NAT_CATEGORY"."NAT_CAT_NO" IS '카테고리 번호';

COMMENT ON COLUMN "NAT_CATEGORY"."NAT_VALUE" IS '나라 이름';

DROP TABLE "ATTACHMENT";

CREATE TABLE "ATTACHMENT" (
	"FILE_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(255)		NOT NULL,
	"CHANGE_NAME"	VARCHAR2(255)		NOT NULL,
	"FILE_PATH"	VARCHAR2(1000)		NULL,
	"UPLOAD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"FILE_LEVEL"	NUMBER		NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NULL,
	"PE_NO"	NUMBER		NULL,
	"RV_NO"	NUMBER		NULL,
	"PRODUCT_NO"	NUMBER		NULL,
	"STEP_NO"	NUMBER		NULL
);

COMMENT ON COLUMN "ATTACHMENT"."FILE_LEVEL" IS '(1대표사진/2본문사진)';

COMMENT ON COLUMN "ATTACHMENT"."PE_NO" IS '레시피 번호';

COMMENT ON COLUMN "ATTACHMENT"."RV_NO" IS '리뷰번호';

COMMENT ON COLUMN "ATTACHMENT"."PRODUCT_NO" IS '식재료 번호';

COMMENT ON COLUMN "ATTACHMENT"."STEP_NO" IS '요리순서 번호';

DROP TABLE "PQNA_ANSWER";

CREATE TABLE "PQNA_ANSWER" (
	"PQNA_NO"	NUMBER		NOT NULL,
	"PQNA_WRITER"	VARCHAR2(20)	DEFAULT 'admin'	NULL,
	"PQNA_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"STATUS"	VARCHAR2(10)	DEFAULT 'Y'	NULL
);

COMMENT ON COLUMN "PQNA_ANSWER"."PQNA_NO" IS '1:1문의사항 번호';

COMMENT ON COLUMN "PQNA_ANSWER"."PQNA_WRITER" IS '답변 작성자';

COMMENT ON COLUMN "PQNA_ANSWER"."PQNA_CONTENT" IS '답변 내용';

COMMENT ON COLUMN "PQNA_ANSWER"."CREATE_DATE" IS '답변 날짜';

COMMENT ON COLUMN "PQNA_ANSWER"."MODIFY_DATE" IS '수정날짜';

COMMENT ON COLUMN "PQNA_ANSWER"."STATUS" IS '삭제여부';

DROP TABLE "RECIPE_COOK_STEP";

CREATE TABLE "RECIPE_COOK_STEP" (
	"STEP_NO"	NUMBER		NOT NULL,
	"PE_NO"	NUMBER		NOT NULL,
	"STEP_COOKNO"	NUMBER		NULL,
	"STEP_CONTENT"	VARCHAR2(4000)		NULL
);

COMMENT ON COLUMN "RECIPE_COOK_STEP"."PE_NO" IS '레시피 번호';

COMMENT ON COLUMN "RECIPE_COOK_STEP"."STEP_COOKNO" IS '요리 순서';

COMMENT ON COLUMN "RECIPE_COOK_STEP"."STEP_CONTENT" IS '요리 순서 내용';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"USER_ID"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_NO"
);

ALTER TABLE "RECIPE" ADD CONSTRAINT "PK_RECIPE" PRIMARY KEY (
	"PE_NO"
);

ALTER TABLE "QNA" ADD CONSTRAINT "PK_QNA" PRIMARY KEY (
	"QNA_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "PQNA" ADD CONSTRAINT "PK_PQNA" PRIMARY KEY (
	"PQNA_NO"
);

ALTER TABLE "CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY (
	"CART_NO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"RV_NO"
);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
	"PR_NO"
);

ALTER TABLE "ORDERTABLE" ADD CONSTRAINT "PK_ORDER" PRIMARY KEY (
	"ORDER_NO"
);

ALTER TABLE "QNA_ANSWER" ADD CONSTRAINT "PK_QNA_ANSWER" PRIMARY KEY (
	"QNA_NO"
);

ALTER TABLE "PRO_CATEGORY" ADD CONSTRAINT "PK_PRO_CATEGORY" PRIMARY KEY (
	"PRO_CAT_NO"
);

ALTER TABLE "KIND_CATEGORY" ADD CONSTRAINT "PK_KIND_CATEGORY" PRIMARY KEY (
	"KIND_CAT_NO"
);

ALTER TABLE "NAT_CATEGORY" ADD CONSTRAINT "PK_NAT_CATEGORY" PRIMARY KEY (
	"NAT_CAT_NO"
);

ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "PK_ATTACHMENT" PRIMARY KEY (
	"FILE_NO"
);

ALTER TABLE "PQNA_ANSWER" ADD CONSTRAINT "PK_PQNA_ANSWER" PRIMARY KEY (
	"PQNA_NO"
);

ALTER TABLE "RECIPE_COOK_STEP" ADD CONSTRAINT "PK_RECIPE_COOK_STEP" PRIMARY KEY (
	"STEP_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_NAT_CATEGORY_TO_MEMBER_1" FOREIGN KEY (
	"FAVORITE_FOOD"
)
REFERENCES "NAT_CATEGORY" (
	"NAT_CAT_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_MEMBER_TO_NOTICE_1" FOREIGN KEY (
	"NOTICE_WRITER"
)
REFERENCES "MEMBER" (
	"USER_ID"
);

ALTER TABLE "RECIPE" ADD CONSTRAINT "FK_MEMBER_TO_RECIPE_1" FOREIGN KEY (
	"PE_WRITER"
)
REFERENCES "MEMBER" (
	"USER_ID"
);

ALTER TABLE "RECIPE" ADD CONSTRAINT "FK_NAT_CATEGORY_TO_RECIPE_1" FOREIGN KEY (
	"NAT_CAT_NO"
)
REFERENCES "NAT_CATEGORY" (
	"NAT_CAT_NO"
);

ALTER TABLE "RECIPE" ADD CONSTRAINT "FK_KIND_CATEGORY_TO_RECIPE_1" FOREIGN KEY (
	"KIND_CAT_NO"
)
REFERENCES "KIND_CATEGORY" (
	"KIND_CAT_NO"
);

ALTER TABLE "RECIPE" ADD CONSTRAINT "FK_PRO_CATEGORY_TO_RECIPE_1" FOREIGN KEY (
	"PRO_CAT_NO"
)
REFERENCES "PRO_CATEGORY" (
	"PRO_CAT_NO"
);

ALTER TABLE "QNA" ADD CONSTRAINT "FK_PRODUCT_TO_QNA_1" FOREIGN KEY (
	"PRODUCT_NO"
)
REFERENCES "PRODUCT" (
	"PR_NO"
);

ALTER TABLE "QNA" ADD CONSTRAINT "FK_MEMBER_TO_QNA_1" FOREIGN KEY (
	"QNA_WRITER"
)
REFERENCES "MEMBER" (
	"USER_ID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"COMMENT_WRITER"
)
REFERENCES "MEMBER" (
	"USER_ID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_RECIPE_TO_COMMENT_1" FOREIGN KEY (
	"REF_PE_NO"
)
REFERENCES "RECIPE" (
	"PE_NO"
);

ALTER TABLE "PQNA" ADD CONSTRAINT "FK_MEMBER_TO_PQNA_1" FOREIGN KEY (
	"PQNA_WRITER"
)
REFERENCES "MEMBER" (
	"USER_ID"
);

ALTER TABLE "CART" ADD CONSTRAINT "FK_MEMBER_TO_CART_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
);

ALTER TABLE "CART" ADD CONSTRAINT "FK_PRODUCT_TO_CART_1" FOREIGN KEY (
	"PRO_NO"
)
REFERENCES "PRODUCT" (
	"PR_NO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_1" FOREIGN KEY (
	"RV_WRITER"
)
REFERENCES "MEMBER" (
	"USER_ID"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_PRODUCT_TO_REVIEW_1" FOREIGN KEY (
	"RV_PRO"
)
REFERENCES "PRODUCT" (
	"PR_NO"
);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_PRO_CATEGORY_TO_PRODUCT_1" FOREIGN KEY (
	"PRO_CAT_NO"
)
REFERENCES "PRO_CATEGORY" (
	"PRO_CAT_NO"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_MEMBER_TO_LIKE_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_RECIPE_TO_LIKE_1" FOREIGN KEY (
	"PE_NO"
)
REFERENCES "RECIPE" (
	"PE_NO"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_PRODUCT_TO_LIKE_1" FOREIGN KEY (
	"PR_NO"
)
REFERENCES "PRODUCT" (
	"PR_NO"
);

ALTER TABLE "RECIPE_SAUCE" ADD CONSTRAINT "FK_RECIPE_TO_RECIPE_SAUCE_1" FOREIGN KEY (
	"PE_NO"
)
REFERENCES "RECIPE" (
	"PE_NO"
);

ALTER TABLE "ORDERTABLE" ADD CONSTRAINT "FK_MEMBER_TO_ORDER_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"USER_ID"
);

ALTER TABLE "QNA_ANSWER" ADD CONSTRAINT "FK_QNA_TO_QNA_ANSWER_1" FOREIGN KEY (
	"QNA_NO"
)
REFERENCES "QNA" (
	"QNA_NO"
);

ALTER TABLE "RECIPE_PRODUCT" ADD CONSTRAINT "FK_RECIPE_TO_RECIPE_PRODUCT_1" FOREIGN KEY (
	"PE_NO"
)
REFERENCES "RECIPE" (
	"PE_NO"
);

ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "FK_RECIPE_TO_ATTACHMENT_1" FOREIGN KEY (
	"PE_NO"
)
REFERENCES "RECIPE" (
	"PE_NO"
);

ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "FK_REVIEW_TO_ATTACHMENT_1" FOREIGN KEY (
	"RV_NO"
)
REFERENCES "REVIEW" (
	"RV_NO"
);

ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "FK_PRODUCT_TO_ATTACHMENT_1" FOREIGN KEY (
	"PRODUCT_NO"
)
REFERENCES "PRODUCT" (
	"PR_NO"
);


ALTER TABLE "PQNA_ANSWER" ADD CONSTRAINT "FK_PQNA_TO_PQNA_ANSWER_1" FOREIGN KEY (
	"PQNA_NO"
)
REFERENCES "PQNA" (
	"PQNA_NO"
);

ALTER TABLE "RECIPE_COOK_STEP" ADD CONSTRAINT "FK_PE_NO" FOREIGN KEY (
	"PE_NO"
)
REFERENCES "RECIPE" (
	"PE_NO"
);

DROP SEQUENCE SEQ_ORDER_NO;
DROP SEQUENCE SEQ_CART_NO;
DROP SEQUENCE SEQ_FILE_NO;
DROP SEQUENCE SEQ_RV_NO;
DROP SEQUENCE SEQ_PR_NO;
DROP SEQUENCE SEQ_QNA_NO;
DROP SEQUENCE SEQ_PE_NO;
DROP SEQUENCE SEQ_PQNA_NO;
DROP SEQUENCE SEQ_PRO_CAT_NO;
DROP SEQUENCE SEQ_NAT_CAT_NO;
DROP SEQUENCE SEQ_KIND_CAT_NO;
DROP SEQUENCE SEQ_STEP_NO;
DROP SEQUENCE SEQ_COMMENT_NO;
DROP SEQUENCE SEQ_NOTICE_NO;

CREATE SEQUENCE SEQ_ORDER_NO
NOCACHE;

CREATE SEQUENCE SEQ_CART_NO
NOCACHE;

CREATE SEQUENCE SEQ_FILE_NO
NOCACHE;

CREATE SEQUENCE SEQ_RV_NO
NOCACHE;

CREATE SEQUENCE SEQ_PR_NO
NOCACHE;

CREATE SEQUENCE SEQ_QNA_NO
NOCACHE;

CREATE SEQUENCE SEQ_PE_NO
NOCACHE;

CREATE SEQUENCE SEQ_PQNA_NO
NOCACHE;

CREATE SEQUENCE SEQ_PRO_CAT_NO
NOCACHE;

CREATE SEQUENCE SEQ_NAT_CAT_NO
NOCACHE;

CREATE SEQUENCE SEQ_KIND_CAT_NO
NOCACHE;

CREATE SEQUENCE SEQ_STEP_NO
NOCACHE;

CREATE SEQUENCE SEQ_COMMENT_NO
NOCACHE;

CREATE SEQUENCE SEQ_NOTICE_NO
NOCACHE;

INSERT INTO NAT_CATEGORY
VALUES (1, '한식');

INSERT INTO NAT_CATEGORY
VALUES (2, '중식');

INSERT INTO NAT_CATEGORY
VALUES (3, '일식');

INSERT INTO NAT_CATEGORY
VALUES (4, '양식');

INSERT INTO NAT_CATEGORY
VALUES (5, '기타');

INSERT INTO KIND_CATEGORY
VALUES (1, '쌀');

INSERT INTO KIND_CATEGORY
VALUES (2, '밀가루');

INSERT INTO KIND_CATEGORY
VALUES (3, '국');

INSERT INTO KIND_CATEGORY
VALUES (4, '반찬');

INSERT INTO KIND_CATEGORY
VALUES (5, '기타');

INSERT INTO PRO_CATEGORY
VALUES (1, '야채/채소');

INSERT INTO PRO_CATEGORY
VALUES (2, '과일');

INSERT INTO PRO_CATEGORY
VALUES (3, '해/수산');

INSERT INTO PRO_CATEGORY
VALUES (4, '정육/계란');

INSERT INTO PRO_CATEGORY
VALUES (5, '기타');

INSERT INTO MEMBER
VALUES ('admin', 'admin', '관리자', 'admin@honja4.com', '서울시 종로구', '010-1234-5678', '관리자', '하', DEFAULT, DEFAULT, DEFAULT, 1);

COMMIT;
